config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: "themes#index"
  resources :themes, only: [:index, :new, :create, :show, :destroy] do
    resources :comments, only: [:index, :create] 
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  with_options presence: true do
    validates :text,length: {maximum: 200}
    validates :sub_theme_num, numericality: { only_integer: true }, inclusion: { in: 1..3 }
  end

  belongs_to :user
  belongs_to :theme
end

app/models/theme.rb
class Theme < ApplicationRecord
  with_options presence: true do
    validates :main_theme, length: {maximum: 50}
    validates :sub_theme_1, length: {maximum: 20}
    validates :sub_theme_2, length: {maximum: 20}
  end

  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.search(search)
    if search != ""
      Theme.where('main_theme LIKE(?)', "%#{search}%")
    else
      Theme.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :email,                 uniqueness: { case_sensitive: false }
    validates :password,              format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  end

  has_many :themes
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    redirect_to theme_path(params[:theme_id])
  end

  def create
    comment = Comment.create(comment_params)
    l_created_at = l comment.created_at 
    render json: { comment: comment,
                   user_name: comment.user.name,
                   l_created_at: l_created_at }
  end

  private

  def comment_params
    params.require(
      :comment
    ).permit(
      :text
    ).merge(
      user_id: current_user.id, theme_id: params[:theme_id], sub_theme_num: params['sub-theme-btn']
    )
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @themes = Theme.all.includes(:comments)
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      redirect_to theme_path(@theme.id)
    else
      render :new
    end
  end

  def show
    @theme = Theme.find(params[:id])
    @comment = Comment.new
    @comments = @theme.comments.includes(:user).order('created_at DESC')
  end

  def destroy
    theme = Theme.find(params[:id])
    if current_user.id == theme.user.id
      if theme.destroy
        redirect_back(fallback_location: root_path)
      else
        render :index
      end
    else
      redirect_to root_path
    end
  end

  def search
    @themes = Theme.search(params[:keyword])
    render :index
  end

  private

  def theme_params
    params.require(
      :theme
    ).permit(
      :main_theme, :sub_theme_1, :sub_theme_2
    ).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def show
    @user = User.find(current_user.id)
    @themes = @user.themes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioOnyo55</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
</div>

app/views/shared/_header.html.erb
<header class="top-page-header">

  <div class="theme-header" id="top">
  <div class="header-content">  
    <%= link_to "varytweet", root_path, class:"top-link" %>
    <a href="#top" class="move-top">トップへ移動</a>

    <div class="nav">
      <ul class='lists-right'>
        <% if user_signed_in? %>
          <li><%= link_to "テーマ作成", new_theme_path, class: "theme-new" %></li>
          <li><%= link_to current_user.name, users_show_path, class: "user-name btn" %> </li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout btn"%> </li> 
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login btn" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up btn" %></li>
        <%end%>
      </ul>
    </div>
  </div>
</div>

</header>

app/views/shared/_second_header.html.erb
<div class="second-header" >
  <%= link_to "varytweet", root_path, class:"top-link" %>
  <div class="nav">
      <ul class='lists-right'>
        <% if user_signed_in? %>
          <li><%= link_to current_user.name, users_show_path, class: "user-name btn" %> </li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout btn"%> </li> 
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login btn" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up btn" %></li>
        <%end%>
      </ul>
    </div>
</div>

app/views/shared/_themes.html.erb
<div class="theme-wrapper" data-comments-count="<%=themes.comments.count%>">
  <%= link_to theme_path(themes.id),class:"themes" do %>
    <div class="theme-content">
      <div class="theme-left">
        <h1 class="main-theme"><%=themes.main_theme%></h1>
        <ul class="sub-theme-list">
          <li class="sub-theme-blue"><%=themes.sub_theme_1%></li>
          <li class="theme-or"> or </li> 
          <li class="sub-theme-red"><%=themes.sub_theme_2%></li>
        </ul>
      </div>
      <div class="theme-right">
        <p class="comments-num"><%=themes.comments.count%></p>
        <h2>コメント</h2>
      </div>
    </div>
  <% end %>
  <div class="theme-menu">
    <% if user_signed_in? && current_user.id == themes.user.id%>
       <input type="checkbox" id="menu-check-<%=themes.id%>" class="menu-hidden" >
       <label for="menu-check-<%=themes.id%>" class="menu-open"><span></span></label>
       <nav class="menu">
         <ul class="menu-list">
           <li><%= link_to "削除",theme_path(themes.id),method: :delete%></li>
         </ul>
       </nav>
       <div class="cover">
       </div>
    <% end %>
  </div>
</div>

app/views/themes/index.html.erb
<%= render "shared/header" %> 

<div class="main-wrapper">
  <div class="title-main">
    <div class="title-wrap">
      <div class="title-content">
        <h2 class="title">varytweet</h1>
        <%# <p>description</p> %>
      </div>
    </div>
  </div>

  <div class="theme-index">
    <div class="form-content">
      <div class="search-form">
        <p>テーマを検索する</p>
        <%= form_with url:search_themes_path,local: true,class: "search-input", method: :get do |f|%>
          <%= f.text_area :keyword, class:"search-text" %>
          <%= f.submit "検索", class:"search-submit" %>
        <% end %>
      </div>
      <div class="theme-sort-wrap">
        <p>並べ替え</p>
        <select class="theme-sort-menu" name="theme-sort" id="theme-sort">
          <option value="#">---</option>
          <option value="many">コメントの多い順</option>
          <option value="few">コメントの少ない順</option>
        </select>
      </div>
    </div>

    <div class="users-theme" id = "theme-area">
      <%= render partial: "shared/themes", collection: @themes%>
    </div>

  </div>

</div>

app/views/themes/new.html.erb
<%=render "shared/second_header"%>
<div class="new-theme-wrap">
  <h1 class="post-theme">テーマ投稿</h1>
  <%= form_with model: @theme,class:"theme-form", url: themes_path, local: true do |f| %>
    <%= render 'shared/error_message', model: f.object %>

    <div class="theme-group">
      <div class="theme-text-wrap">
        <label class="theme-text">メインテーマ</label>
      </div>
      <%= f.text_area :main_theme, class:"input-theme", id:"main_theme", placeholder:"例）きのこ派？たけのこ派？"%>
    </div>

    <div class="sub-theme-group">
      <div class="theme-text-wrap">
        <label class="theme-text">サブテーマ</label>
      </div>
      <div class="sub-theme-wrap">
        <%= f.text_area :sub_theme_1, class:"input-sub-blue",placeholder:"例）きのこ派" %>
        <p class="or">OR</p>
        <%= f.text_area :sub_theme_2, class:"input-sub-red",placeholder:"例 たけのこ派"%>
      </div>
    </div>

    <div class="theme-submit">
      <%= f.submit "投稿する", class:"theme-submit-btn"%>
    </div>
  <%end%>
</div>

app/views/themes/show.html.erb
<%= render "shared/header" %>

<div class="theme-show">

  <div class="content-wrap">
    <div class="menu-wrap">
      <div class="menu-box">
        <h2 class="sort-text">並べ替え</h2>
        <div class="sort-menu">
          <p>通常</p>
          <ul>
            <li><button type = "button" id="new">投稿の新しい順</button></li>
            <li><button type = "button" id="old">投稿の古い順</button></li>
            </ul>
          <p>色が連続しない</p>
          <ul>
            <li><button type = "button" id="dc-new">投稿の新しい順</button></li>
            <li><button type = "button" id="dc-old">投稿の古い順</button></li>
          </ul>
        </div>
      </div> 
    </div>

    <div class="comment-area">
      <div class="form-wrap">
        <% if user_signed_in?%>
          <%= form_with model: [@theme, @comment],class:"post-form",id:"comment-form"  do |f| %>
            <ul class="post-menu">
              <label class="sub-blue sub-label">
                <li class="sub-li">
                  <%= f.radio_button :sub_theme_num,1,name:"sub-theme-btn" %><%=@theme.sub_theme_1%>
                </li>
              </label>
              <label class="sub-red sub-label">
                <li class="sub-li">
                  <%= f.radio_button :sub_theme_num,2,name:"sub-theme-btn"  %><%=@theme.sub_theme_2%>
                </li>
              </label>
              <label class="sub-pur sub-label">
                <li class="sub-li">
                  <%= f.radio_button :sub_theme_num,3,name:"sub-theme-btn" %>どっちでも
                </li>
              </label>
            </ul>
            <div class="comment-post">
              <%= f.text_area :text,placeholder:"サブテーマを選択してください", class:"post-text-area",id:"post-text",disabled: true%>
              <div class="post-menu" id="theme-id" data-theme-id=<%=@theme.id%>>
                <%= f.submit "投稿する", class:"comment-submit", id:"com-submit",disabled: true%>
              </div>
            </div> 
          <% end %>
        <% else %>
          <div class="login-message">
            <p class="message-text">
              コメントの投稿には<%=link_to"ログイン",new_user_session_path,class: "login-message"%>が必要です
            </p>
          </div>
        <%end%>
      </div>

      <div class="comment-box" id="com-box">
        <% @comments.each do |comment|%>
          <div class="comment"  data-id=<%=comment.id%> data-sub-theme=<%=comment.sub_theme_num%>>
            <div class="comment-info">
              <h3 class="user-name"><%=comment.user.name%></h3>
              <p class="created-at"><%=l comment.created_at%></p>
            </div>
            <%=comment.text%>
          </div>
        <% end %>
      </div>
    </div>

    <div class="theme-wrap">
      <div class="theme-box">
        <h1 class="main-theme-show"><%=@theme.main_theme%></h1>
        <ul class="sub-theme-show">
          <li class="sub-blue"><%=@theme.sub_theme_1%></li>
          <li class="sub-or">or</li>
          <li class="sub-red"><%=@theme.sub_theme_2%></li>
        </ul>
      </div>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<%=render "shared/header"%>

<div class="mypage-main">
  <div class="user-info-main">
    <div class="user-info-wrap">
      <div class="user-info">
        <div class="user-icon">
          <%= image_tag "test-user-icon.png"%>
        </div>
        <h1 class="mypage-user-name"><%=@user.name%></h1>
      </div>
    </div>
  </div>
  <div class="user-post-wrap">
    <div class="user-post-tab">
      <div class="theme-tag">
        <p>投稿テーマ一覧<p>
      </div>
      <div class="comment-tag"></div>
    </div>
    <div class="users-theme">
      <%= render partial: "shared/themes", collection: @themes%>
    </div>
  </div>
</div>